src/App.test.jsx

- Unit Test 에러를 수정하기 위함
- matcher 수정

Fix unit test error

---

package-lock.json
package.json

- 개발 환경 향상시키기 위함
- husky의 pre-push 설정 수정
- puppeteer 버전 업그레이드

Enhance development environment

---

services/api.js

- Enhance first deploy
- Use remote url instead of localhost url
- 이전에 1차 배포를 했는데, localhost에서만 데이터 보이는 문제점을 발견했다.
- 이를 계기로 배포시, 여러 기기에서 테스트해봐야하는 것을 느꼈다.

[#14] Enhance first deploy

---

src/App.jsx

필요없는 코드를 삭제하기 위해 작업을 했습니다.
`div` 태그를 삭제했습니다.
무엇인가를 더 추가할 수 없을까? 보다 무엇인가를 더 뺄 수 없을까?가 더 좋다

Remove reduntant div

---

src/DevLinksContainer.jsx
src/HomePage.jsx

loading 메시지를 보여주는 책임을 옮기는 작업을 했습니다.
loading 메시지를 보여주는 책임을 `DevLinksContainer` 컴포넌트로 옮겼습니다.
뿌듯하다

Move responsibility of showing loading message

---

src/App.jsx

import문들을 정렬하기 위해 했습니다.
`React` import문을 가장 위로 옮겼습니다.
정리를 잘하자

Arrange imports

---

fixture/data.js
json-server/db.json
src/App.test.jsx
src/DevLinks.jsx
src/DevLinks.test.jsx
src/DevLinksContainer.jsx
src/DevLinksContainer.test.jsx
src/HomePage.test.jsx
src/Reviews.jsx
src/Reviews.test.jsx
src/Tags.jsx
src/Tags.test.jsx
src/common/reducer.test.js
src/common/slice.js
test/home_page_test.js

- Refactor DevLink Data
* Fix the number of subjects and reviews to 3
* Use review instead of reviewItem
* Use subject instead of subjectItem
* Use subject instead of tag
* Use devLink instead of devlink
- 프로젝트 상황에 따른 작업 우선순위의 중요성을 느꼈다.
- 좀더 깔끔한 워딩을 바꾸고 나니, 읽기 편해져서 기분이 좋았다.

[#45] Refactor DevLink Data

---

src/App.test.jsx
src/DevLinkHeader.jsx
src/DevLinkHeader.test.jsx
src/DevLinks.jsx
src/DevLinks.test.jsx
src/DevLinksContainer.jsx
src/DevLinksContainer.test.jsx
src/Reviews.test.jsx
src/Tags.test.jsx
src/common/utils.js
src/common/utils.test.js

- Refactor some code
- Use isEmpty as a util
- Reveal intent for test by renaming test
- Simplify App's test way for fittng App component's role
- Refactor for revealing more intentions by using destructuring assignment
- utils 잘 활용해보기!
- 테스트 이름을 통해 테스트의 의도를 좀더 드러내보자!!
- 각 컴포넌트의 관심사에 맞게 테스트 하기 
- 이슈 하나씩하나씩 close 시키는 뿌듯함

[#44] Refactor some code

---

src/DevLink.jsx
src/DevLink.test.jsx
src/DevLinks.jsx

- Use DevLink component
- Create DevLink component
- Use DevLink component in DevLinks component
- DevLinks component가 간단해져서 좋았다.

[#43] Use DevLink component

---

src/App.jsx
src/App.test.jsx
src/LoginPage.jsx
src/LoginPage.test.jsx
src/NotFoundPage.jsx
src/NotFoundPage.test.jsx

- Show different pages based on url with React Router
- Create LoginPage temporarily
- Create NotFoundPage
- master로 push할때 마다 배포되는 상황에서 사용자를 고려한 기능추가(ex: 로그인 페이지 준비중 메시지 보여주기 등)도 필요하다고 느꼈다.
- 항상 배포할 수 있는 상태를 유지하는 프로세스가 익숙하지 않아서 다소 힘들다.
- 또한, '지금 개발된 상태에서 사용자가 이렇게 하면 어떻게 화면을 보여줘야하는지'까지 고려해야 하니, 
- 기존 개발 사고보다 더 확장된 사고가 필요하다고 느꼈고, 그로 인해 더 많은 에너지를 쓰게 되는 것 같다.
- 현재는 master branch 만 사용하는데, dev branch를 하나 생성해서, 기능이 완전히 완료될 때 master로 push할까도 고민중이다.

[#52] Show different pages based on url with React Router

---

webpack.config.js

- Update webpack config
- Update webpack config
- 현재 자동으로 deploy가 안되는 상황이다.
- commit 기록을 보면서 언제부터 자동으로 deploy가 안되는지 파악해보니, webpack config을 바뀐 시점부터 deploy가 안되고 었다.
- 그래서, 원래대로 되돌려봤다.

[#57] Resolve routing error (3)

---

src/App.jsx
src/App.test.jsx
test/header_test.js

- Add Links to Header elements
- Remove alert
- Add Link for moving HomePage
- Add Links for moving LoginPage
- 그동안 놓쳤던 E2E 테스트를 작성해서 뿌듯하다.

 Add Links to Header elements

---

front-end/src/DevLink.jsx
front-end/src/DevLinkBody.jsx
front-end/src/DevLinkBody.test.jsx
front-end/src/DevLinkFooter.jsx
front-end/test/header_test.js
front-end/test/home_page_test.js

- Fix test error
- Remove exception handling temporarily in DevLink component
- Remove exception handling temporarily in DevLinkBody component
- Add onClick test in DevLinkBody component
- push 전에 테스트 커버리지 100% 인지 확인하자!
- 기획 변경시 E2E 테스트 먼저 작성하고 시작하자!

Fix test error

---

fixture/data.js
front-end/services/api/__mocks__/api.js
front-end/services/api/api.js
front-end/services/api/api.test.js
front-end/services/firebase/__mocks__/firebase.js
front-end/services/firebase/firebase.js
front-end/src/Header.jsx
front-end/src/Header.test.jsx
front-end/src/common/actions.test.js
front-end/src/common/reducer.test.js
front-end/src/common/slice.js

- resolved #103
- Implement signup
- Update action for logout accoring to adding singup
- Update localStorgae's save structure
- Add User Profile Image in Head
- Git commit 날릴 때, 의도가 들어나도록 쓰는 습관을 기르자!

[#103] 사용자는 처음 로그인시 자동으로 회원가입 된다. 

---

.github/workflows/cicd.yml

Comment out temporarily test in CI/CD

---

.github/workflows/cicd.yml

- reseolved #117 
- Manage E2E test and Unit test separately in CI/CD
- SW 만들 때, 기능 구현도 중요하지만 사용 기술 관련 정책도 꼭! 체크해봐야겠다는 생각을 했다.

[#117] Manage E2E test and Unit test separately in CI/CD

---

.github/workflows/cicd.yml

- Fix E2E TEST in CI/CD
- releated #117 
- Set FIREBASE Config before TEST
-

Set FIREBASE Config before TEST

---

.github/workflows/cicd.yml

- Fix E2E TEST in CI/CD
- related #117
- Add `start-server-and-test start` command at E2E TEST in CI/CD
- 명령어 꼼꼼히 체크하기!

[#117] Fix E2E TEST in CI/CD (3)

---

.github/workflows/cicd.yml

- Fix E2E TEST in CI/CD 
- related #117 
- Update command at Unit TEST and E2E TEST in CI/CD

[#117] Fix 

---

.github/workflows/cicd.yml

Add option for FIREBASE_DATABASE_URL config in CI/CD

---

.github/workflows/cicd.yml

Manage FIREBASE Config(dev) and FIREBASE Config(prod) separately in CI/CD

---

.github/workflows/cicd.yml

- resolved #117 
- Add missing firebase option in CI/CD
- Manange firebase config separately for dev and prod

[#117] Fix E2E test in CI/CD

---

front-end/services/api/__mocks__/api.js
front-end/services/api/api.js
front-end/services/api/api.test.js
front-end/services/firebase/__mocks__/firebase.js
front-end/src/common/actions.test.js
front-end/src/common/slice.js

- resolved #103 
- Implement api for signup
- Implement action for signup
- Implement signup after login in slice.js
- Simplify signup
1. 작업 단위로 잘 나누어진 commit 들이 존재해야지 git 명령어가 유용한다는 것을 깨달았다.
- 기존에 비슷한 작업한 PR(#107) 이 있어서 관련 commit들을 cherry-pick했다.
- 사용하면서 cherry-pick이 유용하려면, pick할 cherry들이 많아야 한다는 것을 알게 되면서, 다시 한번 작업단위로 잘 나누어진 commit 작성이 얼마나 중요한지 알게 되었다.
- 그래서, 이번 PR 만들면서 중간중간 놓친 작업들이 있을 때, 추가 commit을 작성하기 보다 `git rebase -i` 를 활용해서 커밋 메시지 내용 및 커밋 메시지에 포함된 작업 코드를 수정해봤다. 아래 목록이 내가 수정해 본 케이스들이다.
- 1. push 전의 commit 메시지 수정
- 2. push 전의 특정 commit 에 속한 작업 수정
- 3. push 된 commit 메시지 수정
- 4. push 된 특정 commit 작업 수정
- 5. push 된 특정 commit 삭제
- 수정을 계속 해보니, 이제 좀 git 에 대한 자신감이 생긴 것 같다. 앞으로 더 다양한 git 명령어를 써보고 싶다.

[#103] Implement automatic Signup after login

---

front-end/package.json

- resolved #129 
- Set lint and test before push with husky
- TEST와 아름다운 commit이 미래의 나에게 어떤 장점을 주는지 알고 나서 날린 PR이다.
- 앞으로도 계속 유지하자!

[#129] Use husky's pre-push for beautiful commit

---

fixture/data.js
front-end/src/Header.jsx
front-end/src/Header.test.jsx
front-end/src/common/slice.js

- resolved #126 
- Show login User Github Profile in Header

[#126] Show login User Github Profile in Header

---

front-end/src/common/reducer.test.js

- refactor #103 
- Use fixture's accessToken and user in `reducer.test.js`
- 리팩터링은 그때그때 하자!

Use fixture's accessToken and user in `reducer.test.js`

---

front-end/.gitignore

Add `/config` folder in gitignore

---

fixture/data.js
front-end/services/api/__mocks__/api.js
front-end/services/api/api.js
front-end/services/api/api.test.js
front-end/services/firebase/__mocks__/firebase.js
front-end/src/App.jsx
front-end/src/App.test.jsx
front-end/src/Header.jsx
front-end/src/UserInfo.jsx
front-end/src/UserInfo.test.jsx
front-end/src/UserInfoContainer.jsx
front-end/src/UserInfoContainer.test.jsx
front-end/src/UserPage.jsx
front-end/src/UserPage.test.jsx
front-end/src/common/actions.test.js
front-end/src/common/reducer.test.js
front-end/src/common/slice.js
front-end/test/user_page_test.js

- resolved #108 , #127 
- Add E2E for UserPage
- Implement api for getUser
- Implement action for loadDevLinkerInfo
- Implement UserInfo component
- Implement UserInfoContainer component
- Implement UserPage component
- Use UserPage in `App.js`
- Add Link for UserPage in `Header.js`
- git이 나에게 주는 장점을 크게 느꼈다. 이쁜 commit 들이 나오기까지 수정의 수정을 거쳤다. 
- 기존에는 `git reset --soft HEAD^` 명령어로 직접 수정하고 다시 올리고, 멀리 있는 commit 까지 취소하고 다시 올리는 등 너무나 힘들게 git을 사용해온 것 같다.
- 그런데, 이제는 제법 다양한 git 명령어들을 사용해본 덕분에 commit 을 이동시키고 commit 끼리 Merge 등 commit 들을 이리저리 재밌게 가지고 놀 수 있는 것 같다.
- 이제 git이 두렵지 않다😎

[#108] Use UserPage

---

front-end/package-lock.json
front-end/package.json
front-end/test/header_test.js
front-end/test/home_page_test.js
front-end/test/not_found_test.js
front-end/test/user_page_test.js
front-end/yarn.lock

- Upgrade codeceptjs's version from v2 to v3
- Update codeceptjs version in `package.json` 
- Use [new syntax](https://github.com/codeceptjs/CodeceptJS/wiki/Upgrading-to-CodeceptJS-3#1%EF%B8%8F%E2%83%A3-syntax-change)
- 의존성 관리 신경쓰자!

Upgrade codeceptjs's version from v2 to v3

---

front-end/src/common/slice.js

- Fix Logout error
- Remove currentUser in localStorage, when logout
- 기능 구현시, 놓친 것이 없나 꼼꼼히 확인하기!

Fix Logout error

---

web/back-end/functions/firebaseConfig.json

- Remove firebaseconfig value in backend
- Remove firebaseconfig value in backend

Remove firebaseconfig value in backend
